### PR TITLE
fix(index.d.ts): mark some params as optional

### LINKED ISSUE #528: Version 3.3 - types issues
- There are some bugs introduced in 3.3 with types itself
- [Reference](https://github.com/dodona-edu/dodona/pull/5469)
- I'd be happy to fix those minor issues, that my PR  #411 has caused

### PR DESCRIPTION
**Pull request by tomasvn**
- Closes #528

### CODE REVIEW

File: dist/js/glightbox.js [hunk 1]
```diff
@@ -4,6 +4,20 @@
   (global = global || self, global.GLightbox = factory());
 }(this, (function () { 'use strict';
 
+  function _classCallCheck(a, n) {
```
Comment (jorg-vr) [inline dist/js/glightbox.js:7]: Why did you replace readable variable names with single letter versions? This makes the code harder to read and to maintain

**Comment by tomasvn** [comment]
@gingerchew, @biati-digital Any progress on this PR, that introduced some minor bugs, in previous release that was not caught during development. Patch release would solve them before V4

**Comment by gingerchew** [comment]
Wow time sure flies, @biati-digital looks good to me!

**Comment by biati-digital** [comment]
Hi, sorry for the delay. Last year wasn’t kind to me (health issues), but I’m hoping 2025 will be a great year. Happy New Year to everyone!
